dist: trusty
language: python
env:

addons:
  apt:
    packages:
      - build-essential
      - curl
      - git

python:
    - "3.6"

install:
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -o $HOME/miniconda.sh;
    PYTHON_VER="3.6m";
  - cd $HOME && bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export LD_LIBRARY_PATH="$HOME/miniconda/lib:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/miniconda/lib:$LIBRARY_PATH"
  - export CPATH="$HOME/miniconda/include:$CPATH"
  - export CPATH="$HOME/miniconda/include/python$PYTHON_VER:$CPATH"
  - ls $HOME/miniconda/include/python$PYTHON_VER
  - export PATH="$PATH:$PWD/build/bin"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH$PWD/build/lib"
  - printenv
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c conda-forge protobuf numpy
  - cd $TRAVIS_BUILD_DIR && pip install onnx pytest pytest-cov pytest-runner graphviz tensorflow
  - conda install -c caffe2 caffe2
  - cd $TRAVIS_BUILD_DIR && export PYTHONPATH=pwd

script:
    - python -m pytest --cov=tf2onnx --cov-report=term --cov-report=html --cov-report=xml tests
